# Generated by Django 4.0.4 on 2022-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_blogcomment_author_blogcomment_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
